### ISSUE TITLE
Bug (Frontend): "Change Property" link

### ISSUE THREAD

**Issue by geoffblay** [MrEminent42/casamico#22]
Once a property is selected from the properties page, the "Change property" link comes up in the top right. If I use my browser's built-in back button, the "Change property" link does not go away like it does if I use the link itself.

**Comment by MrEminent42** [comment]
@geoffblay okay so this has to do with the way I implemented the "current property": it's stored in a state (aka a variable). I briefly talked to @bri-personal today about how we should sync the URLs to the pages/properties and I think that might be the solution here. I'll implement that this week.

**Comment by MrEminent42** [comment]
For now, I have removed this functionality. The problem is that the Navbar exists outside the router, so it can't see/detect URL changes. Therefore we need to store current property in a state, but that becomes complex and messy with passing down the state-changer function to other parts of the UI. I will revisit this functionality later.
